skip_tags: true
  
matrix:
    fast_finish: true

image: Visual Studio 2017

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017"
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  - mkdir _bld
  - cd _bld
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=%configuration% -DVAR_FUTURES_BUILD_EXAMPLES=ON -DVAR_FUTURES_BUILD_TESTS=ON -DVAR_FUTURES_TEST_COVERAGE=OFF ..

build:
  project: _bld\var_future.sln
 
test_script:
  - cmd: ctest -C %configuration% -VV